# fly.toml app configuration file generated for streamlit-bi on 2023-07-08T10:47:43-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "streamlit-bi"
primary_region = "gru"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
